[unstable]
build-std = ["core", "panic_abort"]
build-std-features = ["optimize_for_size"]

[build]
rustflags = [
    "-Z",
    "unstable-options",
    "-C",
    "opt-level=s",
    "-C",
    "codegen-units=1",
    "-Z",
    "location-detail=none",
    "-Z",
    "fmt-debug=none",
    "-C",
    "panic=immediate-abort"
]
